### ISSUE TITLE
Blue line

### ISSUE THREAD

**Issue by CarmenGarcia1** [openglasgow/opensuggest#3]
Could we change the blue line of Sauchiehall St into a polygon delimiting the Sacuhiehall District? I'll email you a picture of the boundaries soon.

**Comment by aaronbassett** [comment]
http://www.the-di-lab.com/polygon/

If you draw the bounding area using the tool above and then click show paths it will generate all the lat/longs and we can then use those to draw the polygon on our version of the map.

**Comment by CarmenGarcia1** [comment]
Cool tool! Here at the coordinates for the polygon:

(55.86452660172173, -4.271117448806763)(55.86443027355246, -4.268252849578857)(55.8628317931231, -4.254627227783203)(55.86507145343228, -4.253897666931152)(55.86598654629013, -4.253790378570557)(55.8665765289389, -4.254777431488037)(55.866853456479504, -4.256644248962402)(55.867058140783975, -4.258275032043457)(55.867732387334435, -4.259433746337891)(55.87032090375156, -4.26020622253418)(55.869983804407866, -4.264733791351318)(55.86981525363874, -4.267480373382568)(55.86967078096869, -4.267888069152832)(55.87086266442378, -4.271900653839111)(55.868539059792425, -4.274196624755859)(55.86831933350709, -4.276696443557739)(55.865989556428424, -4.276299476623535)(55.86627551850312, -4.271879196166992)(55.86454466322686, -4.271160364151001)(55.86454466322686, -4.271160364151001)

**Comment by aaronbassett** [comment]
Thanks, I'll get this added today.

**Comment by aaronbassett** [comment]
Polygon added d3859487a81ade03e79b2bc01c2a8931d6955753
